import * as vscode from 'vscode';

export function getChatViewHtml(webview: vscode.Webview, extensionUri: vscode.Uri, currentModel: string): string {
  // Helper to check if model is selected
  const isSelected = (val: string) => val === currentModel ? 'selected' : '';

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<style>',
    ':root {',
    '  --bg: #0d1117;',
    '  --input-bg: #161b22;',
    '  --text: #c9d1d9;',
    '  --text-muted: #8b949e;',
    '  --border: #30363d;',
    '  --accent: #58a6ff;',
    '  --accent-dim: rgba(88, 166, 255, 0.1);',
    '  --user-bubble: #1f6feb;',
    '  --ai-bubble: #21262d;',
    '  --success: #3fb950;',
    '  --error: #f85149;',
    '  --font-body: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;',
    '}',
    '* { margin: 0; padding: 0; box-sizing: border-box; }',
    'body {',
    '  font-family: var(--font-body);',
    '  font-size: 14px;',
    '  color: var(--text);',
    '  background: var(--bg);',
    '  height: 100vh;',
    '  display: flex;',
    '  flex-direction: column;',
    '  overflow: hidden;',
    '}',
    '',
    '/* Chat History */',
    '#chat { flex: 1; overflow-y: auto; padding: 24px 20px; scroll-behavior: smooth; }',
    '.msg-group { margin-bottom: 24px; animation: slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1); display: flex; flex-direction: column; }',
    '@keyframes slideUp { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }',
    '',
    '.msg-group.msg-user { align-items: flex-end; }',
    '.msg-group.msg-ai { align-items: flex-start; }',
    '',
    '.msg-content { max-width: 90%; padding: 12px 16px; border-radius: 12px; line-height: 1.5; font-size: 13.5px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }',
    '.msg-user .msg-content { background: var(--user-bubble); color: white; border-bottom-right-radius: 4px; }',
    '.msg-ai .msg-content { background: var(--ai-bubble); color: var(--text); border: 1px solid var(--border); border-bottom-left-radius: 4px; }',
    '.msg-ai.is-error .msg-content { background: rgba(248,81,73,0.1); border-color: var(--error); color: var(--error); }',
    '',
    '.msg-header { margin-bottom: 6px; font-size: 11px; font-weight: 600; color: var(--text-muted); padding: 0 4px; }',
    '',
    '.msg-content pre { background: #0d1117; padding: 16px; border-radius: 8px; overflow-x: auto; margin: 12px 0; border: 1px solid var(--border); position: relative; }',
    '.msg-content code { font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace; font-size: 12.5px; }',
    '.msg-content p { margin-bottom: 10px; }',
    '.msg-content p:last-child { margin-bottom: 0; }',
    '.copy-btn { position: absolute; top: 8px; right: 8px; padding: 4px 10px; font-size: 11px; font-weight: 600; background: #21262d; color: #c9d1d9; border: 1px solid var(--border); border-radius: 6px; cursor: pointer; opacity: 0; transition: all 0.2s; }',
    '.msg-content pre:hover .copy-btn { opacity: 1; }',
    '.copy-btn:hover { background: #30363d; }',
    '',
    '/* Bottom Control Center */',
    '#bottom-area { padding: 16px 20px; background: rgba(13,17,23,0.95); border-top: 1px solid var(--border); backdrop-filter: blur(10px); }',
    '#control-bar { display: flex; align-items: center; justify-content: space-between; gap: 8px; margin-bottom: 12px; flex-wrap: wrap; }',
    '.control-group { display: flex; gap: 8px; align-items: center; flex: 1; flex-wrap: wrap; }',
    '.control-item { background: var(--input-bg); border: 1px solid var(--border); border-radius: 6px; padding: 6px 10px; font-size: 12px; font-weight: 500; color: var(--text-muted); display: flex; align-items: center; gap: 6px; cursor: pointer; transition: all 0.2s; }',
    '.control-item:hover { border-color: var(--text-muted); color: var(--text); }',
    '.control-item.active { background: var(--accent-dim); border-color: var(--accent); color: var(--accent); }',
    'select { background: transparent; border: none; color: inherit; font-size: inherit; font-weight: inherit; font-family: inherit; outline: none; cursor: pointer; appearance: none; padding-right: 12px;}',
    'option { background: var(--input-bg); color: var(--text); }',
    '',
    '#input-wrapper { display: flex; gap: 12px; background: var(--input-bg); border: 1px solid var(--border); border-radius: 12px; padding: 10px 14px; transition: border-color 0.2s; align-items: flex-end; box-shadow: inset 0 1px 2px rgba(0,0,0,0.05); }',
    '#input-wrapper:focus-within { border-color: var(--accent); box-shadow: 0 0 0 1px var(--accent); }',
    '#msg-input { flex: 1; background: transparent; color: var(--text); border: none; font-size: 14px; font-family: inherit; resize: none; min-height: 24px; max-height: 200px; outline: none; padding: 2px 0; line-height: 1.5; }',
    '.send-btn { width: 32px; height: 32px; background: var(--accent); color: #fff; border: none; border-radius: 8px; display: flex; align-items: center; justify-content: center; cursor: pointer; transition: all 0.2s; flex-shrink: 0; box-shadow: 0 2px 4px rgba(88,166,255,0.2); }',
    '.send-btn:hover { background: #79c0ff; transform: translateY(-1px); }',
    '.send-btn:disabled { opacity: 0.5; cursor: not-allowed; transform: none; box-shadow: none; filter: grayscale(1); }',
    '',
    '/* Setup Overlay */',
    '#setup-overlay { position: absolute; inset: 0; background: var(--bg); z-index: 100; display: none; padding: 40px; flex-direction: column; align-items: center; justify-content: center; }',
    '#setup-overlay.active { display: flex; }',
    '.setup-card { background: var(--input-bg); border: 1px solid var(--border); padding: 40px; border-radius: 16px; max-width: 320px; text-align: center; box-shadow: 0 8px 24px rgba(0,0,0,0.2); }',
    '.setup-btn { background: var(--accent); color: #fff; border: none; padding: 12px 24px; border-radius: 8px; font-weight: 600; width: 100%; margin-top: 24px; cursor: pointer; transition: background 0.2s; }',
    '.setup-btn:hover { background: #79c0ff; }',
    '',
    '/* Animations */',
    '#loading-indicator { display: none; align-items: center; gap: 8px; margin-bottom: 20px; padding: 0 20px; }',
    '#loading-indicator.show { display: flex; }',
    '.dot { width: 6px; height: 6px; background: var(--accent); border-radius: 50%; animation: pulse 1s infinite alternate; }',
    '.dot:nth-child(2) { animation-delay: 0.3s; }',
    '.dot:nth-child(3) { animation-delay: 0.6s; }',
    '@keyframes pulse { from { opacity: 0.3; transform: scale(0.8); } to { opacity: 1; transform: scale(1.2); } }',
    '</style>',
    '</head>',
    '<body>',
    '',
    '  <div id="setup-overlay">',
    '    <div class="setup-card" id="setup-step-install">',
    '      <div style="font-size: 40px; margin-bottom: 16px;">✨</div>',
    '      <div style="font-weight: 700; font-size: 18px; margin-bottom: 8px; color: #fff;">Install Gemini CLI</div>',
    '      <div style="color: var(--text-muted); font-size: 13px; line-height: 1.5;">Required to power the intelligent coding assistant.</div>',
    '      <button class="setup-btn" id="install-btn">Install Globally</button>',
    '      <button style="background:none; border:none; color:var(--text-muted); font-size: 12px; margin-top:16px; cursor:pointer;" id="skip-setup">Already have it?</button>',
    '    </div>',
    '    <div class="setup-card" id="setup-step-login" style="display:none;">',
    '      <div style="font-size: 40px; margin-bottom: 16px;">🔑</div>',
    '      <div style="font-weight: 700; font-size: 18px; margin-bottom: 8px; color: #fff;">Authentication</div>',
    '      <div style="color: var(--text-muted); font-size: 13px; line-height: 1.5;">Login with your Google account to access Gemini.</div>',
    '      <button class="setup-btn" id="login-btn">Login via Terminal</button>',
    '    </div>',
    '  </div>',
    '',
    '  <div id="chat"></div>',
    '',
    '  <div id="loading-indicator">',
    '    <div class="dot"></div><div class="dot"></div><div class="dot"></div>',
    '    <span style="font-size: 12px; font-weight: 500; color: var(--text-muted)">Assistant is thinking...</span>',
    '  </div>',
    '',
    '  <div id="bottom-area">',
    '    <div id="control-bar">',
    '      <div class="control-group">',
    '        <div class="control-item tooltip" title="Select Model">',
    '          <span>✨</span>',
    '          <select id="setting-model">',
    `            <option value="default" ${isSelected('default')}>Default CLI Model</option>`,
    `            <option value="gemini-3-flash-preview" ${isSelected('gemini-3-flash-preview')}>Gemini 3 Flash</option>`,
    `            <option value="gemini-3.1-flash-lite-preview" ${isSelected('gemini-3.1-flash-lite-preview')}>Gemini 3.1 Flash</option>`,
    `            <option value="gemini-2.5-flash" ${isSelected('gemini-2.5-flash')}>Gemini 2.5 Flash</option>`,
    `            <option value="gemini-2.5-flash-lite" ${isSelected('gemini-2.5-flash-lite')}>Gemini 2.5 Lite</option>`,
    '          </select>',
    '        </div>',
    '        <div class="control-item" id="yolo-btn" title="Skip Confirmations">',
    '          <span>⚡</span> YOLO <input type="checkbox" id="yolo-checkbox" style="display:none">',
    '        </div>',
    '        <div class="control-item tooltip" title="Switch Session">',
    '          <span>📼</span>',
    '          <select id="setting-session">',
    '            <option value="">New Session</option>',
    '          </select>',
    '        </div>',
    '      </div>',
    '      <div class="control-item" id="clear-chat-btn" title="Clear Chat">',
    '        <span style="font-size: 14px;">🗑️</span>',
    '      </div>',
    '    </div>',
    '    <div id="input-wrapper">',
    '      <textarea id="msg-input" placeholder="Message Gemini... (Shift+Enter for new line)" rows="1"></textarea>',
    '      <button class="send-btn" id="send-btn" title="Send (Enter)">',
    '        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon></svg>',
    '      </button>',
    '    </div>',
    '    <div id="status-line" style="font-size: 11px; font-weight: 500; color: var(--text-muted); margin-top: 10px; display: flex; align-items: center; justify-content: space-between;">',
    '      <div style="display: flex; align-items: center; gap: 6px;">',
    '        <div id="status-icon" style="width: 8px; height: 8px; border-radius: 50%; background: var(--text-muted);"></div>',
    '        <span id="status-text">Connecting...</span>',
    '      </div>',
    '      <div>AI Coding Assistant</div>',
    '    </div>',
    '  </div>',
    '',
    '  <script>',
    '    (function() {',
    '      const vscode = acquireVsCodeApi();',
    '      const chatPane = document.getElementById("chat");',
    '      const inputEl = document.getElementById("msg-input");',
    '      const sendBtn = document.getElementById("send-btn");',
    '      const loading = document.getElementById("loading-indicator");',
    '      const setupOverlay = document.getElementById("setup-overlay");',
    '      ',
    '      // Model selection sync',
    '      const modelSelect = document.getElementById("setting-model");',
    '      modelSelect.addEventListener("change", (e) => {',
    '        vscode.postMessage({ type: "changeModel", model: e.target.value });',
    '      });',
    '',
    '      // YOLO toggle',
    '      const yoloBtn = document.getElementById("yolo-btn");',
    '      const yoloCheck = document.getElementById("yolo-checkbox");',
    '      yoloBtn.addEventListener("click", () => {',
    '        yoloCheck.checked = !yoloCheck.checked;',
    '        yoloBtn.classList.toggle("active", yoloCheck.checked);',
    '      });',
    '',
    '      inputEl.addEventListener("input", () => {',
    '        inputEl.style.height = "auto";',
    '        inputEl.style.height = Math.min(inputEl.scrollHeight, 200) + "px";',
    '      });',
    '',
    '      inputEl.addEventListener("keydown", (e) => {',
    '        if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); }',
    '      });',
    '',
    '      sendBtn.addEventListener("click", sendMessage);',
    '',
    '      function sendMessage() {',
    '        const content = inputEl.value.trim();',
    '        if (!content) return;',
    '        ',
    '        const options = {',
    '          yolo: yoloCheck.checked,',
    '          sessionId: document.getElementById("setting-session").value',
    '        };',
    '',
    '        vscode.postMessage({ type: "sendMessage", content, options });',
    '        inputEl.value = "";',
    '        inputEl.style.height = "auto";',
    '      }',
    '',
    '      document.getElementById("install-btn").addEventListener("click", () => vscode.postMessage({ type: "installGemini" }));',
    '      document.getElementById("login-btn").addEventListener("click", () => vscode.postMessage({ type: "loginGemini" }));',
    '      document.getElementById("skip-setup").addEventListener("click", () => {',
    '        setupOverlay.classList.remove("active");',
    '        vscode.postMessage({ type: "checkStatus" });',
    '      });',
    '      document.getElementById("clear-chat-btn").addEventListener("click", () => vscode.postMessage({ type: "clearChat" }));',
    '      const messageIdMap = new Map();',
    '',
    '      window.addEventListener("message", (e) => {',
    '        const m = e.data;',
    '        switch(m.type) {',
    '          case "newMessage": renderMessage(m.message); break;',
    '          case "updateMessage": updateMessage(m.id, m.content); break;',
    '          case "setLoading": ',
    '            loading.classList.toggle("show", m.value);',
    '            sendBtn.disabled = m.value;',
    '            inputEl.disabled = m.value;',
    '            if(!m.value) setTimeout(() => inputEl.focus(), 100);',
    '            break;',
    '          case "clearChat": chatPane.innerHTML = ""; messageIdMap.clear(); break;',
    '          case "showSetup": setupOverlay.classList.add("active"); break;',
    '          case "setupStep": showSetupStep(m.step); break;',
    '          case "statusUpdate": updateStatus(m.available, m.sessions); break;',
    '        }',
    '      });',
    '',
    '      function updateMessage(id, content) {',
    '        const group = messageIdMap.get(id);',
    '        if (group) {',
    '          const contentEl = group.querySelector(".msg-content");',
    '          contentEl.innerHTML = formatMarkdown(content);',
    '          chatPane.scrollTop = chatPane.scrollHeight;',
    '          attachCopyEvents(group);',
    '        } else {',
    '          renderMessage({ id, role: "assistant", content });',
    '        }',
    '      }',
    '',
    '      function renderMessage(msg) {',
    '        if (messageIdMap.has(msg.id)) return updateMessage(msg.id, msg.content);',
    '',
    '        const group = document.createElement("div");',
    '        group.className = "msg-group msg-" + msg.role;',
    '        group.id = msg.id;',
    '        ',
    '        const header = document.createElement("div");',
    '        header.className = "msg-header";',
    '        header.textContent = msg.role === "user" ? "You" : "Gemini";',
    '        ',
    '        const content = document.createElement("div");',
    '        content.className = "msg-content";',
    '        if (msg.role === "assistant" && msg.content.includes("Error:")) group.classList.add("is-error");',
    '        content.innerHTML = formatMarkdown(msg.content);',
    '        ',
    '        if (msg.role === "user") {',
    '           group.appendChild(content);',
    '        } else {',
    '           group.appendChild(header);',
    '           group.appendChild(content);',
    '        }',
    '        chatPane.appendChild(group);',
    '        messageIdMap.set(msg.id, group);',
    '        chatPane.scrollTop = chatPane.scrollHeight;',
    '        ',
    '        attachCopyEvents(group);',
    '      }',
    '',
    '      function attachCopyEvents(container) {',
    '        container.querySelectorAll(".copy-btn").forEach(btn => {',
    '          if (btn.dataset.hooked) return;',
    '          btn.dataset.hooked = "true";',
    '          btn.addEventListener("click", () => {',
    '            const code = btn.nextElementSibling.textContent;',
    '            navigator.clipboard.writeText(code);',
    '            btn.textContent = "Copied!";',
    '            setTimeout(() => btn.textContent = "Copy", 2000);',
    '          });',
    '        });',
    '      }',
    '',
    '      function formatMarkdown(text) {',
    '        if (!text) return "";',
    '        let result = text;',
    '        ',
    '        // Code blocks',
    '        result = result.replace(/```(\\w*)\\n([\\s\\S]*?)(```|$)/g, (m, lang, code) => {',
    '          return `<pre><button class="copy-btn">Copy</button><code>${escapeHtml(code.trim())}</code></pre>`;',
    '        });',
    '        ',
    '        // Bold',
    '        result = result.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");',
    '        ',
    '        // Inline code',
    '        result = result.replace(/`([^`\\n]+)`/g, "<code>$1</code>");',
    '        ',
    '        // Tables (simple support)',
    '        if (result.includes("|")) {',
    '           const lines = result.split("\\n");',
    '           let inTable = false;',
    '           result = lines.map(line => {',
    '             if (line.includes("|") && line.trim().startsWith("|")) {',
    '               inTable = true;',
    '               return `| ${line.split("|").filter(x => x.trim()).join(" | ")} |`;',
    '             }',
    '             inTable = false;',
    '             return line;',
    '           }).join("\\n");',
    '        }',
    '',
    '        // Paragraphs & Breaks',
    '        const paragraphs = result.split(/\\n\\n+/);',
    '        return paragraphs.map(p => {',
    '          const lines = p.split("\\n");',
    '          return `<p>${lines.join("<br>")}</p>`;',
    '        }).join("");',
    '      }',
    '',
    '      function escapeHtml(t) {',
    '        const d = document.createElement("div");',
    '        d.textContent = t; return d.innerHTML;',
    '      }',
    '',
    '      function showSetupStep(step) {',
    '        document.querySelectorAll(".setup-card").forEach(c => c.style.display = "none");',
    '        document.getElementById("setup-step-" + step).style.display = "block";',
    '        if (step === "check") setTimeout(() => vscode.postMessage({ type: "checkStatus" }), 2000);',
    '      }',
    '',
    '      function updateStatus(available, sessions) {',
    '        const icon = document.getElementById("status-icon");',
    '        const text = document.getElementById("status-text");',
    '        if (available) {',
    '          icon.style.background = "var(--success)";',
    '          text.textContent = "Ready";',
    '          text.style.color = "var(--success)";',
    '          setupOverlay.classList.remove("active");',
    '          const sessionSelect = document.getElementById("setting-session");',
    '          sessionSelect.innerHTML = \'<option value="">New Session</option>\';',
    '          if (sessions) {',
    '            sessions.forEach(s => {',
    '              const opt = document.createElement("option");',
    '              opt.value = opt.textContent = s;',
    '              sessionSelect.appendChild(opt);',
    '            });',
    '          }',
    '        } else {',
    '           icon.style.background = "var(--error)";',
    '           text.textContent = "CLI Missing";',
    '           text.style.color = "var(--error)";',
    '        }',
    '      }',
    '',
    '      vscode.postMessage({ type: "checkStatus" });',
    '      inputEl.focus();',
    '    })();',
    '  </script>',
    '</body>',
    '</html>',
  ].join('\n');
}
